   version: '3.8'

   services:
     postgres:
       image: postgres:latest
       environment:
         POSTGRES_DB: cricsdb
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
       volumes:
         - postgres-data:/var/lib/postgresql/data

     backend:
       image: farooquespacey/cric-fuss
       ports:
         - "8080:8080"
       environment:
         SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cricsdb
         SPRING_DATASOURCE_USERNAME: postgres
         SPRING_DATASOURCE_PASSWORD: postgres
         SPRING_DATASOURCE_DDL_AUTO: update
       depends_on:
         - postgres

   volumes:
     postgres-data:
